[phases.setup]
nixPkgs = ["python311", "gdal", "geos", "proj", "postgresql"]

[phases.install]
cmds = ["python -m venv /opt/venv && . /opt/venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt"]

[phases.build]
cmds = ["cd backend && . /opt/venv/bin/activate && python manage.py collectstatic --noinput"]

[start]
cmd = ". /opt/venv/bin/activate && cd backend && gunicorn config.wsgi --bind 0.0.0.0:$PORT --log-file -"
